kind: pipeline
type: docker
name: publish nightly

trigger:
  event:
    - promote
  target:
    - nightly

steps:
  - name: docker publish api
    image: plugins/docker
    pull: always
    settings:
      dockerfile: Dockerfile.api
      repo: iexechub/iexec-market-api
      tags:
        - ${DRONE_BRANCH}
        - ${DRONE_BRANCH}-${DRONE_COMMIT}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: docker publish watcher
    image: plugins/docker
    pull: always
    settings:
      dockerfile: Dockerfile.watcher
      repo: iexechub/iexec-market-watcher
      tags:
        - ${DRONE_BRANCH}
        - ${DRONE_BRANCH}-${DRONE_COMMIT}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

---
kind: pipeline
type: docker
name: publish latest

# promote latest on tag semver tags
trigger:
  event:
    - promote
  target:
    - latest
  ref:
    include:
      - refs/tags/v[0-9]*.*[0-9].*[0-9]
    exclude:
      - refs/tags/v*.*.*.*
      - refs/tags/v*-*
      - refs/tags/v*[a-zA-Z]*

steps:
  - name: docker publish api
    image: plugins/docker
    pull: always
    settings:
      dockerfile: Dockerfile.api
      repo: iexechub/iexec-market-api
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: docker publish watcher
    image: plugins/docker
    pull: always
    settings:
      dockerfile: Dockerfile.watcher
      repo: iexechub/iexec-market-watcher
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
