kind: pipeline
type: docker
name: api-default

trigger:
  event:
    exclude:
      - promote
      - pull_request

steps:
  - name: wait services initialization
    image: bash
    commands:
      - sleep 30

  - name: api test
    image: node:22.14-alpine3.21
    commands:
      - apk update && apk upgrade
      - node -v
      - cd api/
      - npm ci
      - npm run ci-test-token
      - npm run ci-test-token-enterprise
      - npm run ci-test-native

services:
  - name: chain-token
    image: iexechub/poco-chaintest:5.3.0-token-parity
    pull: true
  - name: chain-native
    image: iexechub/poco-chaintest:5.3.0-native-parity
    pull: true
  - name: mongo
    image: mongo:latest
    pull: true
  - name: redis
    image: redis:alpine
    pull: true

---
kind: pipeline
type: docker
name: watcher-default

trigger:
  event:
    exclude:
      - promote
      - pull_request

steps:
  - name: wait services initialization
    image: bash
    commands:
      - sleep 30

  - name: watcher test
    image: node:22.14-alpine3.21
    commands:
      - apk update && apk upgrade
      - node -v
      - cd watcher/
      - npm ci
      - npm run ci-test-token
      - npm run ci-test-native

services:
  - name: chain-token
    image: iexechub/poco-chaintest:5.3.0-token-parity
    pull: true
  - name: chain-native
    image: iexechub/poco-chaintest:5.3.0-native-parity
    pull: true
  - name: mongo
    image: mongo:latest
    pull: true
  - name: redis
    image: redis:alpine
    pull: true

---
kind: pipeline
type: docker
name: publish api dry-run

trigger:
  event:
    exclude:
      - promote

steps:
  - name: docker publish dry-run
    image: plugins/docker
    pull: always
    settings:
      repo: iexechub/iexec-market-api
      dockerfile: Dockerfile.api
      dry_run: true

---
kind: pipeline
type: docker
name: publish watcher dry-run

trigger:
  event:
    exclude:
      - promote

steps:
  - name: docker publish dry-run
    image: plugins/docker
    pull: always
    settings:
      repo: iexechub/iexec-market-watcher
      dockerfile: Dockerfile.watcher
      dry_run: true

---
kind: pipeline
type: docker
name: publish nightly

trigger:
  event:
    - promote
  target:
    - nightly

steps:
  - name: docker publish api
    image: plugins/docker
    pull: always
    settings:
      dockerfile: Dockerfile.api
      repo: iexechub/iexec-market-api
      tags:
        - ${DRONE_BRANCH}
        - ${DRONE_BRANCH}-${DRONE_COMMIT}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: docker publish watcher
    image: plugins/docker
    pull: always
    settings:
      dockerfile: Dockerfile.watcher
      repo: iexechub/iexec-market-watcher
      tags:
        - ${DRONE_BRANCH}
        - ${DRONE_BRANCH}-${DRONE_COMMIT}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

---
kind: pipeline
type: docker
name: publish latest

# promote latest on tag semver tags
trigger:
  event:
    - promote
  target:
    - latest
  ref:
    include:
      - refs/tags/v[0-9]*.*[0-9].*[0-9]
    exclude:
      - refs/tags/v*.*.*.*
      - refs/tags/v*-*
      - refs/tags/v*[a-zA-Z]*

steps:
  - name: docker publish api
    image: plugins/docker
    pull: always
    settings:
      dockerfile: Dockerfile.api
      repo: iexechub/iexec-market-api
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: docker publish watcher
    image: plugins/docker
    pull: always
    settings:
      dockerfile: Dockerfile.watcher
      repo: iexechub/iexec-market-watcher
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
