networks:
  database:
  webproxy:

services:
  mongo:
    restart: unless-stopped
    image: mongo:6.0.3
    expose:
      - "27017"
    networks:
      - database

  redis:
    restart: unless-stopped
    image: redis:7.2.5-alpine
    command: redis-server --appendonly yes
    expose:
      - "6379"
    networks:
      - database

  iexec-market-api:
    restart: unless-stopped
    image: iexechub/iexec-market-api
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      # - DEBUG=iexec-market-api:*
      - DEBUG_COLORS=true
      - CHAINS=ARBITRUM_MAINNET
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
      - ARBITRUM_MAINNET_ETH_RPC_HOST=${ARBITRUM_MAINNET_ETH_RPC_HOST}
      - ARBITRUM_MAINNET_ETH_WS_HOST=${ARBITRUM_MAINNET_ETH_WS_HOST}
      - CREATE_INDEX=${CREATE_INDEX}
    depends_on:
      - mongo
      - redis
    networks:
      - webproxy
      - database

  arbitrum-mainnet-watcher:
    restart: unless-stopped
    image: iexechub/iexec-market-watcher
    environment:
      - DEBUG=iexec-watcher:app
      - DEBUG_COLORS=true
      - CHAIN=ARBITRUM_MAINNET
      - BLOCKS_BATCH_SIZE=100000
      - ETH_RPC_HOST=${ARBITRUM_MAINNET_ETH_RPC_HOST}
      - ETH_WS_HOST=${ARBITRUM_MAINNET_ETH_WS_HOST}
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
      - CREATE_INDEX=${CREATE_INDEX}
    depends_on:
      - mongo
      - redis
    networks:
      - database
