FROM node:22.14-alpine3.21

RUN mkdir -p /app
WORKDIR /app

RUN apk update && apk upgrade

COPY watcher/package.json .
COPY watcher/package-lock.json .
COPY watcher/generateEsModulesFromJson.cjs .
RUN npm ci --omit=dev

COPY watcher/src ./src

CMD ["npm", "start"]
