FROM node:16.19.0-alpine

RUN mkdir -p /app
WORKDIR /app

RUN apk update && apk upgrade

COPY api/package.json package.json
COPY api/package-lock.json package-lock.json
RUN npm ci --omit=dev

COPY api/src ./src
COPY api/openapi.yaml .

CMD ["npm", "start"]
