FROM node:14.17-alpine

RUN mkdir -p /app
WORKDIR /app

RUN apk update && apk upgrade

COPY watcher/package.json package.json
COPY watcher/package-lock.json package-lock.json
RUN npm ci --only=production

COPY watcher/src ./src

CMD ["npm", "start"]
