FROM node:22.14-alpine3.21

RUN mkdir -p /app
WORKDIR /app

RUN apk update && apk upgrade

COPY api/package.json .
COPY api/package-lock.json .
COPY api/generateEsModulesFromJson.cjs .
RUN npm ci --omit=dev

COPY api/src ./src
COPY api/openapi.yaml .

CMD ["npm", "start"]
