name: Watcher PR checks
on:
  pull_request:
    paths: ["watcher/**"]

concurrency:
  group: ${{ github.ref }}-watcher-pr-checks
  cancel-in-progress: true

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "watcher/package-lock.json"

      - name: Install dependencies
        working-directory: watcher
        run: |
          npm ci
          npm run codegen

      - name: Check format
        working-directory: watcher
        run: npm run check-format

      - name: Lint
        working-directory: watcher
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "watcher/package-lock.json"

      - name: Install dependencies
        working-directory: watcher
        run: |
          npm ci
          npm run codegen

      - name: Start e2e test stack
        working-directory: watcher
        run: npm run start-test-stack

      - name: Run tests
        working-directory: watcher
        run: npm test

  docker-dry-run:
    uses: ./.github/workflows/reusable-watcher-docker.yml
    with:
      dry-run: true
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-password: ${{ secrets.DOCKERHUB_PAT }}
